export const specialists = [
  {
    name: "Dr. Amina Khan",
    appointmentTime: "9:00 AM - 12:00 PM",
    fees: 150,
    category: "Cardiologist",
    hospital: "City Heart Hospital",
    gender: "Female",
    id: 1,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Bilal Ahmed",
    appointmentTime: "2:00 PM - 6:00 PM",
    fees: 200,
    category: "Dermatologist",
    hospital: "Skin Care Clinic",
    gender: "Male",
    id: 2,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Fatima Noor",
    appointmentTime: "10:00 AM - 1:00 PM",
    fees: 180,
    category: "Pediatrician",
    hospital: "Children's Health Center",
    gender: "Female",
    id: 3,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Amir Malik",
    appointmentTime: "3:00 PM - 5:00 PM",
    fees: 220,
    category: "Orthopedic",
    hospital: "City Orthopedic Hospital",
    gender: "Male",
    id: 4,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Hina Syed",
    appointmentTime: "11:00 AM - 4:00 PM",
    fees: 175,
    category: "Gynecologist",
    hospital: "Women's Health Clinic",
    gender: "Female",
    id: 5,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Usman Raza",
    appointmentTime: "1:00 PM - 3:00 PM",
    fees: 190,
    category: "General Practitioner",
    hospital: "Main Street Clinic",
    gender: "Male",
    id: 6,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Zainab Qureshi",
    appointmentTime: "9:30 AM - 12:30 PM",
    fees: 160,
    category: "Ophthalmologist",
    hospital: "Vision Care Center",
    gender: "Female",
    id: 7,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Hassan Malik",
    appointmentTime: "4:00 PM - 7:00 PM",
    fees: 210,
    category: "Surgeon",
    hospital: "City Surgical Center",
    gender: "Male",
    id: 8,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Sara Ahmed",
    appointmentTime: "8:00 AM - 11:00 AM",
    fees: 145,
    category: "Endocrinologist",
    hospital: "HealthPlus Clinic",
    gender: "Female",
    id: 9,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Khalid Bashir",
    appointmentTime: "10:30 AM - 1:30 PM",
    fees: 200,
    category: "Urologist",
    hospital: "Men's Health Clinic",
    gender: "Male",
    id: 10,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Aliya Khan",
    appointmentTime: "1:00 PM - 3:00 PM",
    fees: 170,
    category: "Psychiatrist",
    hospital: "Mental Wellness Center",
    gender: "Female",
    id: 11,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Salman Farooq",
    appointmentTime: "2:30 PM - 5:30 PM",
    fees: 210,
    category: "Radiologist",
    hospital: "Radiology Center",
    gender: "Male",
    id: 12,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Nida Malik",
    appointmentTime: "9:00 AM - 11:00 AM",
    fees: 155,
    category: "Nutritionist",
    hospital: "Nutrition Center",
    gender: "Female",
    id: 13,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Omar Rashid",
    appointmentTime: "11:00 AM - 2:00 PM",
    fees: 195,
    category: "Oncologist",
    hospital: "Cancer Care Center",
    gender: "Male",
    id: 14,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Fatimah Nasir",
    appointmentTime: "3:00 PM - 6:00 PM",
    fees: 165,
    category: "Geriatrician",
    hospital: "Senior Health Center",
    gender: "Female",
    id: 15,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Yasir Khan",
    appointmentTime: "10:00 AM - 1:00 PM",
    fees: 175,
    category: "Allergist",
    hospital: "Allergy Clinic",
    gender: "Male",
    id: 16,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Asma Javed",
    appointmentTime: "1:30 PM - 4:30 PM",
    fees: 185,
    category: "Pulmonologist",
    hospital: "Lung Health Center",
    gender: "Female",
    id: 17,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Imran Khan",
    appointmentTime: "8:30 AM - 12:00 PM",
    fees: 210,
    category: "Neurosurgeon",
    hospital: "Neuro Center",
    gender: "Male",
    id: 18,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Sadaf Baig",
    appointmentTime: "12:00 PM - 3:00 PM",
    fees: 160,
    category: "Cardiac Surgeon",
    hospital: "Heart Hospital",
    gender: "Female",
    id: 19,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Raheel Ahmad",
    appointmentTime: "9:00 AM - 11:00 AM",
    fees: 155,
    category: "Pediatric Surgeon",
    hospital: "Children's Hospital",
    gender: "Male",
    id: 20,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Noor Fatima",
    appointmentTime: "1:00 PM - 4:00 PM",
    fees: 165,
    category: "Hematologist",
    hospital: "Blood Care Center",
    gender: "Female",
    id: 21,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Waseem Javed",
    appointmentTime: "11:00 AM - 2:00 PM",
    fees: 190,
    category: "Pathologist",
    hospital: "Lab Services",
    gender: "Male",
    id: 22,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Zain Hussain",
    appointmentTime: "2:00 PM - 5:00 PM",
    fees: 200,
    category: "Plastic Surgeon",
    hospital: "Cosmetic Clinic",
    gender: "Male",
    id: 23,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Shaista Malik",
    appointmentTime: "9:30 AM - 12:30 PM",
    fees: 175,
    category: "Anesthesiologist",
    hospital: "Surgical Services",
    gender: "Female",
    id: 24,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
  {
    name: "Dr. Haris Khan",
    appointmentTime: "10:00 AM - 1:00 PM",
    fees: 190,
    category: "Reproductive Endocrinologist",
    hospital: "Fertility Clinic",
    gender: "Male",
    id: 25,
    image: "https://preview.colorlib.com/theme/medicalcenter/assets/img/gallery/team1.png",
    socials: {
      twitter: "#",
      instagram: "#",
      facebook: "#",
      pinterest: "#",
    },
  },
];
